[16-Aug-25 07:55:16 - INFO] - ZeMusic.core.mongo - يتم رفع البيانات...
[16-Aug-25 07:55:16 - INFO] - ZeMusic.core.mongo - تم رفع البيانات.
[16-Aug-25 07:55:16 - INFO] - ZeMusic.core.dir - تم اكتمال التحميل.
[16-Aug-25 07:55:16 - INFO] - ZeMusic.core.git - Git Client Found [VPS DEPLOYER]
[16-Aug-25 07:55:16 - INFO] - ZeMusic.misc - Local Database Initialized.
[16-Aug-25 07:55:16 - INFO] - ZeMusic.core.bot - يتم تشغيل البوت..
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/ZeMusic/__main__.py", line 19, in <module>
    from ZeMusic.core.call import Mody
  File "/workspace/ZeMusic/core/call.py", line 9, in <module>
    from pytgcalls import PyTgCalls, StreamType
ImportError: cannot import name 'StreamType' from 'pytgcalls' (/home/ubuntu/.local/lib/python3.13/site-packages/pytgcalls/__init__.py)
[PATCH] ntgcalls compatibility aliases created successfully
